# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/FPGA_Dev/Stopwatch/ethernet.cache/wt [current_project]
set_property parent.project_path C:/FPGA_Dev/Stopwatch/ethernet.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_repo_paths c:/FPGA_Dev/Phase_3 [current_project]
set_property ip_output_repo c:/FPGA_Dev/Stopwatch/ethernet.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files C:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_1/design_1_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_1/design_1_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_1/design_1_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_1/design_1_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_1/design_1_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_1/design_1_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_1/design_1_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_1/design_1_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_1/design_1_microblaze_0_axi_intc_1.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_1/design_1_microblaze_0_axi_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_1/design_1_microblaze_0_axi_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_1/design_1_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_1/design_1_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_1/design_1_clk_wiz_1_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_1/design_1_clk_wiz_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_1/design_1_clk_wiz_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_1/design_1_rst_clk_wiz_1_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_1/design_1_rst_clk_wiz_1_100M_1.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_1/design_1_rst_clk_wiz_1_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_mii_to_rmii_0_1/design_1_mii_to_rmii_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_mii_to_rmii_0_1/design_1_mii_to_rmii_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_1/design_1_axi_ethernetlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_1/design_1_axi_ethernetlite_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_1/design_1_axi_ethernetlite_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_1/design_1_axi_ethernetlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_1/design_1_axi_timer_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_1/design_1_axi_timer_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_xbar_3/design_1_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_75M_0/design_1_rst_mig_7series_0_75M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_75M_0/design_1_rst_mig_7series_0_75M_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_75M_0/design_1_rst_mig_7series_0_75M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files C:/FPGA_Dev/Stopwatch/ethernet.srcs/sources_1/bd/design_1/design_1.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/FPGA_Dev/Stopwatch/ethernet.srcs/constrs_1/imports/ethernet/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/FPGA_Dev/Stopwatch/ethernet.srcs/constrs_1/imports/ethernet/Nexys4DDR_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
