# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir w:/desktop/phase_3/stopwatch_1/ip_repo/edit_Master_controller_v2_0.cache/wt [current_project]
set_property parent.project_path w:/desktop/phase_3/stopwatch_1/ip_repo/edit_Master_controller_v2_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_repo_paths {
  w:/Desktop/Phase_3/StopWatch_1/ip_repo/Master_controller_2.0
  w:/Desktop/Phase_3/StopWatch_1
  w:/Desktop/lab_sources
  w:/Desktop/lab_sources/PMOD_tutorial
} [current_project]
set_property ip_output_repo w:/desktop/phase_3/stopwatch_1/ip_repo/edit_Master_controller_v2_0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  W:/Desktop/Phase_3/StopWatch_1/ip_repo/Master_controller_2.0/src/debounce.v
  W:/Desktop/Phase_3/StopWatch_1/ip_repo/Master_controller_2.0/src/up_down_counter.v
  W:/Desktop/Phase_3/StopWatch_1/ip_repo/Master_controller_2.0/src/top.v
  W:/Desktop/Phase_3/StopWatch_1/ip_repo/Master_controller_2.0/src/clk_divider.v
  W:/Desktop/Phase_3/StopWatch_1/ip_repo/Master_controller_2.0/src/BCD_Decoder.v
  w:/Desktop/Phase_3/StopWatch_1/ip_repo/Master_controller_2.0/hdl/Master_controller_v2_0_S00_AXI.v
  w:/Desktop/Phase_3/StopWatch_1/ip_repo/Master_controller_2.0/hdl/Master_controller_v2_0.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Master_controller_v2_0 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Master_controller_v2_0.dcp

catch { report_utilization -file Master_controller_v2_0_utilization_synth.rpt -pb Master_controller_v2_0_utilization_synth.pb }
